I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script call
    call Dia2_Raul_Priscila
  File "game/scripts/Dia2RaulPriscila.rpy", line 103, in script
    jump Escolha_1_continuacao
ScriptError: could not find label 'Escolha_1_continuacao'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script call
    call Dia2_Raul_Priscila
  File "game/scripts/Dia2RaulPriscila.rpy", line 103, in script
    jump Escolha_1_continuacao
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\User\Backup\rafae\Programas\Ren'py\renpy-8.0.3-sdk\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'Escolha_1_continuacao'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.0.3.22090809
Heart Beat 1.0
Mon Nov 21 10:18:43 2022
